# shellcheck disable=SC2034,SC2154
handle_firewall_command() {
    case "$command_type" in
        firewall.set_zone)
            payload_file=/tmp/wrtmonitor-command-payload; printf '%s' "$command_payload" >"$payload_file"; zone_section="$(json_get_string "$payload_file" '@.section')"; zone_name="$(json_get_string "$payload_file" '@.name')"; zone_networks="$(jsonfilter -i "$payload_file" -e '@.networks[*]' 2>/dev/null)"; zone_input="$(json_get_string "$payload_file" '@.input')"; zone_output="$(json_get_string "$payload_file" '@.output')"; zone_forward="$(json_get_string "$payload_file" '@.forward')"; masquerade="$(json_get_bool "$payload_file" '@.masquerade')"; rm -f "$payload_file"; zone_ref="${zone_section:-wrtmonitor_zone_$zone_name}"; uci set "firewall.$zone_ref=zone"; uci set "firewall.$zone_ref.name=$zone_name"; uci set "firewall.$zone_ref.input=$zone_input"; uci set "firewall.$zone_ref.output=$zone_output"; uci set "firewall.$zone_ref.forward=$zone_forward"; uci set "firewall.$zone_ref.masq=$( [ "$masquerade" = true ] && echo 1 || echo 0 )"; uci -q delete "firewall.$zone_ref.network" || true; for item in $zone_networks; do uci add_list "firewall.$zone_ref.network=$item"; done
            if uci commit firewall && service_action firewall reload 20 >/dev/null 2>&1; then result="$(command_success_result "firewall zone updated")"; else status=failed; result="$(command_failed_result "failed to update firewall zone")"; fi
            ;;
        firewall.delete_zone)
            payload_file=/tmp/wrtmonitor-command-payload; printf '%s' "$command_payload" >"$payload_file"; zone_section="$(json_get_string "$payload_file" '@.section')"; zone_name="$(json_get_string "$payload_file" '@.name')"; rm -f "$payload_file"; zone_ref="${zone_section:-wrtmonitor_zone_$zone_name}"
            if [ "$zone_name" = lan ] || [ "$zone_name" = wan ]; then status=failed; result="$(command_failed_result "core firewall zone cannot be deleted")"
            elif uci -q delete "firewall.$zone_ref" && uci commit firewall && service_action firewall reload 20 >/dev/null 2>&1; then result="$(command_success_result "firewall zone deleted")"; else status=failed; result="$(command_failed_result "firewall zone not found")"; fi
            ;;
        firewall.set_forwarding)
            payload_file=/tmp/wrtmonitor-command-payload; printf '%s' "$command_payload" >"$payload_file"; forward_section="$(json_get_string "$payload_file" '@.section')"; forward_src="$(json_get_string "$payload_file" '@.src')"; forward_dest="$(json_get_string "$payload_file" '@.dest')"; forward_enabled="$(json_get_bool "$payload_file" '@.enabled')"; rm -f "$payload_file"; forward_ref="${forward_section:-wrtmonitor_forward_${forward_src}_${forward_dest}}"
            if [ "$forward_enabled" = true ]; then uci set "firewall.$forward_ref=forwarding"; uci set "firewall.$forward_ref.src=$forward_src"; uci set "firewall.$forward_ref.dest=$forward_dest"; else uci -q delete "firewall.$forward_ref" || true; fi
            if uci commit firewall && service_action firewall reload 20 >/dev/null 2>&1; then result="$(command_success_result "firewall forwarding updated")"; else status=failed; result="$(command_failed_result "failed to update forwarding")"; fi
            ;;
        firewall.delete_forwarding)
            payload_file=/tmp/wrtmonitor-command-payload; printf '%s' "$command_payload" >"$payload_file"; forward_section="$(json_get_string "$payload_file" '@.section')"; forward_src="$(json_get_string "$payload_file" '@.src')"; forward_dest="$(json_get_string "$payload_file" '@.dest')"; rm -f "$payload_file"; forward_ref="${forward_section:-wrtmonitor_forward_${forward_src}_${forward_dest}}"
            if uci -q delete "firewall.$forward_ref" && uci commit firewall && service_action firewall reload 20 >/dev/null 2>&1; then result="$(command_success_result "firewall forwarding deleted")"; else status=failed; result="$(command_failed_result "firewall forwarding not found")"; fi
            ;;
        firewall.set_rule)
            payload_file=/tmp/wrtmonitor-command-payload; printf '%s' "$command_payload" >"$payload_file"; rule_section="$(json_get_string "$payload_file" '@.section')"; rule_name="$(json_get_string "$payload_file" '@.name')"; rule_src="$(json_get_string "$payload_file" '@.src')"; rule_dest="$(json_get_string "$payload_file" '@.dest')"; rule_proto="$(json_get_string "$payload_file" '@.protocol')"; rule_src_ip="$(json_get_string "$payload_file" '@.src_ip')"; rule_dest_ip="$(json_get_string "$payload_file" '@.dest_ip')"; rule_src_port="$(json_get_string "$payload_file" '@.src_port')"; rule_dest_port="$(json_get_string "$payload_file" '@.dest_port')"; rule_target="$(json_get_string "$payload_file" '@.target')"; rm -f "$payload_file"; rule_ref="${rule_section:-wrtmonitor_rule_$rule_name}"; [ "$rule_proto" != tcpudp ] || rule_proto='tcp udp'; uci set "firewall.$rule_ref=rule"; uci set "firewall.$rule_ref.name=$rule_name"; for option in src dest src_ip dest_ip src_port dest_port; do uci -q delete "firewall.$rule_ref.$option" || true; done; [ "$rule_src" = '*' ] || uci set "firewall.$rule_ref.src=$rule_src"; [ "$rule_dest" = '*' ] || uci set "firewall.$rule_ref.dest=$rule_dest"; uci set "firewall.$rule_ref.proto=$rule_proto"; uci set "firewall.$rule_ref.target=$rule_target"; [ -z "$rule_src_ip" ] || uci set "firewall.$rule_ref.src_ip=$rule_src_ip"; [ -z "$rule_dest_ip" ] || uci set "firewall.$rule_ref.dest_ip=$rule_dest_ip"; [ -z "$rule_src_port" ] || uci set "firewall.$rule_ref.src_port=$rule_src_port"; [ -z "$rule_dest_port" ] || uci set "firewall.$rule_ref.dest_port=$rule_dest_port"
            if uci commit firewall && service_action firewall reload 20 >/dev/null 2>&1; then result="$(command_success_result "firewall rule updated")"; else status=failed; result="$(command_failed_result "failed to update firewall rule")"; fi
            ;;
        firewall.delete_rule)
            payload_file=/tmp/wrtmonitor-command-payload; printf '%s' "$command_payload" >"$payload_file"; rule_section="$(json_get_string "$payload_file" '@.section')"; rule_name="$(json_get_string "$payload_file" '@.name')"; rm -f "$payload_file"; rule_ref="${rule_section:-wrtmonitor_rule_$rule_name}"; if uci -q delete "firewall.$rule_ref" && uci commit firewall && service_action firewall reload 20 >/dev/null 2>&1; then result="$(command_success_result "firewall rule deleted")"; else status=failed; result="$(command_failed_result "rule not found")"; fi
            ;;
        firewall.set_redirect)
            payload_file=/tmp/wrtmonitor-command-payload; printf '%s' "$command_payload" >"$payload_file"; redirect_section="$(json_get_string "$payload_file" '@.section')"; redirect_name="$(json_get_string "$payload_file" '@.name')"; redirect_enabled="$(json_get_bool "$payload_file" '@.enabled')"; redirect_src="$(json_get_string "$payload_file" '@.src')"; redirect_dest="$(json_get_string "$payload_file" '@.dest')"; redirect_proto="$(json_get_string "$payload_file" '@.protocol')"; redirect_src_ip="$(json_get_string "$payload_file" '@.src_ip')"; redirect_src_port="$(json_get_string "$payload_file" '@.src_port')"; redirect_dest_ip="$(json_get_string "$payload_file" '@.dest_ip')"; redirect_dest_port="$(json_get_string "$payload_file" '@.dest_port')"; redirect_target="$(json_get_string "$payload_file" '@.target')"; rm -f "$payload_file"; redirect_ref="${redirect_section:-wrtmonitor_redirect_$redirect_name}"
            uci set "firewall.$redirect_ref=redirect"; uci set "firewall.$redirect_ref.name=$redirect_name"; uci set "firewall.$redirect_ref.enabled=$( [ "$redirect_enabled" = true ] && printf 1 || printf 0 )"; uci set "firewall.$redirect_ref.src=$redirect_src"; uci set "firewall.$redirect_ref.dest=$redirect_dest"; uci set "firewall.$redirect_ref.proto=$redirect_proto"; uci set "firewall.$redirect_ref.target=$redirect_target"; for option in src_ip src_dport dest_ip dest_port; do uci -q delete "firewall.$redirect_ref.$option" || true; done; [ -z "$redirect_src_ip" ] || uci set "firewall.$redirect_ref.src_ip=$redirect_src_ip"; [ -z "$redirect_src_port" ] || uci set "firewall.$redirect_ref.src_dport=$redirect_src_port"; [ -z "$redirect_dest_ip" ] || uci set "firewall.$redirect_ref.dest_ip=$redirect_dest_ip"; [ -z "$redirect_dest_port" ] || uci set "firewall.$redirect_ref.dest_port=$redirect_dest_port"
            if uci commit firewall && service_action firewall reload 20 >/dev/null 2>&1; then result="$(command_success_result "NAT redirect updated")"; else status=failed; result="$(command_failed_result "failed to update NAT redirect")"; fi
            ;;
        firewall.delete_redirect)
            payload_file=/tmp/wrtmonitor-command-payload; printf '%s' "$command_payload" >"$payload_file"; redirect_section="$(json_get_string "$payload_file" '@.section')"; redirect_name="$(json_get_string "$payload_file" '@.name')"; rm -f "$payload_file"; redirect_ref="${redirect_section:-wrtmonitor_redirect_$redirect_name}"
            if uci -q delete "firewall.$redirect_ref" && uci commit firewall && service_action firewall reload 20 >/dev/null 2>&1; then result="$(command_success_result "NAT redirect deleted")"; else status=failed; result="$(command_failed_result "NAT redirect not found")"; fi
            ;;
        firewall.set_port_forward)
            payload_file="/tmp/wrtmonitor-command-payload"; printf '%s' "$command_payload" >"$payload_file"
            forward_section="$(json_get_string "$payload_file" '@.section')"; forward_name="$(json_get_string "$payload_file" '@.name')"; forward_proto="$(json_get_string "$payload_file" '@.protocol')"; external_port="$(json_get_number "$payload_file" '@.external_port')"; internal_ip="$(json_get_string "$payload_file" '@.internal_ip')"; internal_port="$(json_get_number "$payload_file" '@.internal_port')"; rm -f "$payload_file"
            forward_ref="${forward_section:-wrtmonitor_redirect_$forward_name}"; [ "$forward_proto" != "tcpudp" ] || forward_proto="tcp udp"
            backup_file="$(backup_config firewall "$command_id" "$command_type" || true)"
            if [ -n "$backup_file" ] && uci set "firewall.$forward_ref=redirect" && uci set "firewall.$forward_ref.name=WrtMonitor-$forward_name" && uci set "firewall.$forward_ref.src=wan" && uci set "firewall.$forward_ref.dest=lan" && uci set "firewall.$forward_ref.proto=$forward_proto" && uci set "firewall.$forward_ref.src_dport=$external_port" && uci set "firewall.$forward_ref.dest_ip=$internal_ip" && uci set "firewall.$forward_ref.dest_port=$internal_port" && uci set "firewall.$forward_ref.target=DNAT" && uci commit firewall && service_action firewall reload 20 >/dev/null 2>&1; then
                result="$(command_success_result "port forwarding rule saved" "\"backup\":\"$(json_escape "$backup_file")\",\"name\":\"$(json_escape "$forward_name")\"")"
            else status="failed"; result="$(command_failed_result "failed to save port forwarding rule")"; fi
            ;;
        firewall.delete_port_forward)
            payload_file="/tmp/wrtmonitor-command-payload"; printf '%s' "$command_payload" >"$payload_file"; forward_section="$(json_get_string "$payload_file" '@.section')"; forward_name="$(json_get_string "$payload_file" '@.name')"; rm -f "$payload_file"; forward_ref="${forward_section:-wrtmonitor_redirect_$forward_name}"
            backup_file="$(backup_config firewall "$command_id" "$command_type" || true)"
            if [ -n "$backup_file" ] && uci -q delete "firewall.$forward_ref" && uci commit firewall && service_action firewall reload 20 >/dev/null 2>&1; then result="$(command_success_result "port forwarding rule deleted" "\"backup\":\"$(json_escape "$backup_file")\"")"; else status="failed"; result="$(command_failed_result "port forwarding rule not found")"; fi
            ;;
        *) return 1 ;;
    esac
    return 0
}
