# shellcheck disable=SC2034,SC2154
handle_vpn_command() {
    case "$command_type" in
        vpn.wireguard.set_interface)
            payload_file=/tmp/wrtmonitor-command-payload; printf '%s' "$command_payload" >"$payload_file"; wg_name="$(json_get_string "$payload_file" '@.name')"; wg_enabled="$(json_get_bool "$payload_file" '@.enabled')"; wg_mode="$(json_get_string "$payload_file" '@.mode')"; wg_addresses="$(jsonfilter -i "$payload_file" -e '@.addresses[*]' 2>/dev/null || true)"; wg_port="$(json_get_number "$payload_file" '@.listen_port')"; wg_private="$(json_get_string "$payload_file" '@.private_key')"; wg_mtu="$(json_get_number "$payload_file" '@.mtu')"; rm -f "$payload_file"
            if [ -z "$wg_private" ]; then wg_private="$(wg genkey 2>/dev/null || true)"; fi
            uci set "network.$wg_name=interface"; uci set "network.$wg_name.proto=wireguard"; uci set "network.$wg_name.private_key=$wg_private"; uci set "network.$wg_name.listen_port=$wg_port"; uci set "network.$wg_name.mtu=$wg_mtu"; uci set "network.$wg_name.wrtmonitor_mode=$wg_mode"; uci set "network.$wg_name.disabled=$( [ "$wg_enabled" = true ] && printf 0 || printf 1 )"; uci -q delete "network.$wg_name.addresses" || true
            for wg_address in $wg_addresses; do uci add_list "network.$wg_name.addresses=$wg_address"; done
            if [ -n "$wg_private" ] && uci commit network; then result="$(command_success_result "WireGuard interface updated" "\"interface\":\"$(json_escape "$wg_name")\"")"; (sleep 2; ifdown "$wg_name" >/dev/null 2>&1 || true; if [ "$wg_enabled" = true ]; then ifup "$wg_name" >/dev/null 2>&1 || true; fi) & else status=failed; result="$(command_failed_result "failed to update WireGuard interface")"; fi
            ;;
        vpn.wireguard.delete_interface)
            payload_file=/tmp/wrtmonitor-command-payload; printf '%s' "$command_payload" >"$payload_file"; wg_name="$(json_get_string "$payload_file" '@.name')"; rm -f "$payload_file"
            if [ "$(uci -q get "network.$wg_name.proto" 2>/dev/null || true)" != wireguard ]; then status=failed; result="$(command_failed_result "WireGuard interface not found")"
            else
                ifdown "$wg_name" >/dev/null 2>&1 || true
                for peer_ref in $(uci -q show network 2>/dev/null | sed -n "s/^network\.\([^.=]*\)=wireguard_$wg_name$/\1/p"); do uci -q delete "network.$peer_ref" || true; done
                if uci -q delete "network.$wg_name" && uci commit network && service_action network reload 30 >/dev/null 2>&1; then result="$(command_success_result "WireGuard interface deleted")"; else status=failed; result="$(command_failed_result "failed to delete WireGuard interface")"; fi
            fi
            ;;
        vpn.wireguard.set_peer)
            payload_file=/tmp/wrtmonitor-command-payload; printf '%s' "$command_payload" >"$payload_file"; wg_iface="$(json_get_string "$payload_file" '@.interface')"; peer_name="$(json_get_string "$payload_file" '@.name')"; peer_public="$(json_get_string "$payload_file" '@.public_key')"; peer_psk="$(json_get_string "$payload_file" '@.preshared_key')"; peer_allowed="$(jsonfilter -i "$payload_file" -e '@.allowed_ips[*]' 2>/dev/null || true)"; peer_endpoint="$(json_get_string "$payload_file" '@.endpoint')"; peer_keepalive="$(json_get_number "$payload_file" '@.persistent_keepalive')"; peer_route="$(json_get_bool "$payload_file" '@.route_allowed_ips')"; rm -f "$payload_file"; peer_ref="wrtmonitor_wgpeer_${wg_iface}_${peer_name}"
            uci set "network.$peer_ref=wireguard_$wg_iface"; uci set "network.$peer_ref.wrtmonitor_name=$peer_name"; uci set "network.$peer_ref.public_key=$peer_public"; uci set "network.$peer_ref.route_allowed_ips=$( [ "$peer_route" = true ] && printf 1 || printf 0 )"; uci set "network.$peer_ref.persistent_keepalive=$peer_keepalive"; uci -q delete "network.$peer_ref.preshared_key" || true; [ -z "$peer_psk" ] || uci set "network.$peer_ref.preshared_key=$peer_psk"; uci -q delete "network.$peer_ref.allowed_ips" || true; for allowed in $peer_allowed; do uci add_list "network.$peer_ref.allowed_ips=$allowed"; done; uci -q delete "network.$peer_ref.endpoint_host" || true; uci -q delete "network.$peer_ref.endpoint_port" || true
            if [ -n "$peer_endpoint" ]; then peer_port="${peer_endpoint##*:}"; peer_host="${peer_endpoint%:*}"; peer_host="$(printf '%s' "$peer_host" | sed 's/^\[//; s/\]$//')"; uci set "network.$peer_ref.endpoint_host=$peer_host"; uci set "network.$peer_ref.endpoint_port=$peer_port"; fi
            if uci commit network && ifup "$wg_iface" >/dev/null 2>&1; then result="$(command_success_result "WireGuard peer updated")"; else status=failed; result="$(command_failed_result "failed to update WireGuard peer")"; fi
            ;;
        vpn.wireguard.delete_peer)
            payload_file=/tmp/wrtmonitor-command-payload; printf '%s' "$command_payload" >"$payload_file"; wg_iface="$(json_get_string "$payload_file" '@.interface')"; peer_name="$(json_get_string "$payload_file" '@.name')"; rm -f "$payload_file"; if uci -q delete "network.wrtmonitor_wgpeer_${wg_iface}_${peer_name}" && uci commit network; then ifup "$wg_iface" >/dev/null 2>&1 || true; result="$(command_success_result "WireGuard peer deleted")"; else status=failed; result="$(command_failed_result "WireGuard peer not found")"; fi
            ;;
        vpn.wireguard.export_peer)
            payload_file=/tmp/wrtmonitor-command-payload; printf '%s' "$command_payload" >"$payload_file"; wg_iface="$(json_get_string "$payload_file" '@.interface')"; peer_name="$(json_get_string "$payload_file" '@.name')"; rm -f "$payload_file"; peer_ref="wrtmonitor_wgpeer_${wg_iface}_${peer_name}"; server_private="$(uci -q get "network.$wg_iface.private_key" 2>/dev/null || true)"; server_public="$(printf '%s' "$server_private" | wg pubkey 2>/dev/null || true)"; peer_allowed="$(uci -q get "network.$peer_ref.allowed_ips" 2>/dev/null || true)"; server_port="$(uci -q get "network.$wg_iface.listen_port" 2>/dev/null || echo 51820)"; if [ -n "$server_public" ] && [ -n "$peer_allowed" ]; then export_config="[Interface]\nPrivateKey = <PRIVATE_KEY>\nAddress = $peer_allowed\n\n[Peer]\nPublicKey = $server_public\nAllowedIPs = 0.0.0.0/0, ::/0\nEndpoint = <SERVER_HOST>:$server_port\nPersistentKeepalive = 25"; result="$(command_success_result "WireGuard peer profile exported" "\"config\":\"$(json_escape "$export_config")\"")"; else status=failed; result="$(command_failed_result "WireGuard peer or interface not found")"; fi
            ;;
        vpn.openvpn.set_client)
            payload_file=/tmp/wrtmonitor-command-payload; printf '%s' "$command_payload" >"$payload_file"; ovpn_name="$(json_get_string "$payload_file" '@.name')"; ovpn_enabled="$(json_get_bool "$payload_file" '@.enabled')"; ovpn_config="$(json_get_string "$payload_file" '@.config')"; rm -f "$payload_file"; ovpn_ref="wrtmonitor_$ovpn_name"; ovpn_b64="$(printf '%s\n' "$ovpn_config" | base64 | tr -d '\n')"; uci set "openvpn.$ovpn_ref=openvpn"; uci set "openvpn.$ovpn_ref.enabled=$( [ "$ovpn_enabled" = true ] && printf 1 || printf 0 )"; uci set "openvpn.$ovpn_ref.wrtmonitor_name=$ovpn_name"; uci set "openvpn.$ovpn_ref.wrtmonitor_config_b64=$ovpn_b64"
            if openvpn_render_configs && service_action openvpn restart 20 >/dev/null 2>&1; then result="$(command_success_result "OpenVPN client imported")"; else status=failed; result="$(command_failed_result "failed to import OpenVPN client")"; fi
            ;;
        vpn.openvpn.delete_client)
            payload_file=/tmp/wrtmonitor-command-payload; printf '%s' "$command_payload" >"$payload_file"; ovpn_name="$(json_get_string "$payload_file" '@.name')"; rm -f "$payload_file"; ovpn_ref="wrtmonitor_$ovpn_name"; if uci -q delete "openvpn.$ovpn_ref" && uci commit openvpn; then rm -f "${WRTMONITOR_SYSTEM_ROOT:-}/etc/openvpn/wrtmonitor-$ovpn_ref.conf"; service_action openvpn restart 20 >/dev/null 2>&1 || true; result="$(command_success_result "OpenVPN client deleted")"; else status=failed; result="$(command_failed_result "OpenVPN client not found")"; fi
            ;;
        vpn.openvpn.set_enabled)
            payload_file=/tmp/wrtmonitor-command-payload; printf '%s' "$command_payload" >"$payload_file"; ovpn_name="$(json_get_string "$payload_file" '@.name')"; ovpn_enabled="$(json_get_bool "$payload_file" '@.enabled')"; rm -f "$payload_file"; ovpn_ref="wrtmonitor_$ovpn_name"
            if uci -q get "openvpn.$ovpn_ref" >/dev/null 2>&1 && uci set "openvpn.$ovpn_ref.enabled=$( [ "$ovpn_enabled" = true ] && printf 1 || printf 0 )" && uci commit openvpn && openvpn_render_configs && service_action openvpn restart 20 >/dev/null 2>&1; then result="$(command_success_result "OpenVPN profile state updated")"; else status=failed; result="$(command_failed_result "OpenVPN profile not found or service restart failed")"; fi
            ;;
        vpn.openvpn.export_client)
            payload_file=/tmp/wrtmonitor-command-payload; printf '%s' "$command_payload" >"$payload_file"; ovpn_name="$(json_get_string "$payload_file" '@.name')"; rm -f "$payload_file"; ovpn_ref="wrtmonitor_$ovpn_name"; ovpn_b64="$(uci -q get "openvpn.$ovpn_ref.wrtmonitor_config_b64" 2>/dev/null || true)"
            if [ -n "$ovpn_b64" ]; then result="$(command_success_result "OpenVPN profile exported" "\"filename\":\"$(json_escape "$ovpn_name.ovpn")\",\"config_base64\":\"$(json_escape "$ovpn_b64")\"")"; else status=failed; result="$(command_failed_result "OpenVPN profile not found")"; fi
            ;;
        vpn.policy.set)
            payload_file=/tmp/wrtmonitor-command-payload; printf '%s' "$command_payload" >"$payload_file"; policy_section="$(json_get_string "$payload_file" '@.section')"; policy_name="$(json_get_string "$payload_file" '@.name')"; policy_enabled="$(json_get_bool "$payload_file" '@.enabled')"; policy_iface="$(json_get_string "$payload_file" '@.interface')"; policy_source="$(json_get_string "$payload_file" '@.source')"; policy_destination="$(json_get_string "$payload_file" '@.destination')"; policy_protocol="$(json_get_string "$payload_file" '@.protocol')"; rm -f "$payload_file"; policy_ref="${policy_section:-wrtmonitor_$policy_name}"; uci set "pbr.$policy_ref=policy"; uci set "pbr.$policy_ref.name=$policy_name"; uci set "pbr.$policy_ref.enabled=$( [ "$policy_enabled" = true ] && printf 1 || printf 0 )"; uci set "pbr.$policy_ref.interface=$policy_iface"; uci -q delete "pbr.$policy_ref.src_addr" || true; uci -q delete "pbr.$policy_ref.dest_addr" || true; [ -z "$policy_source" ] || uci set "pbr.$policy_ref.src_addr=$policy_source"; [ -z "$policy_destination" ] || uci set "pbr.$policy_ref.dest_addr=$policy_destination"; uci set "pbr.$policy_ref.proto=$policy_protocol"
            [ "$policy_enabled" = true ] && uci set 'pbr.config.enabled=1'
            if uci commit pbr && service_restart_if_enabled pbr config.enabled pbr >/dev/null 2>&1; then result="$(command_success_result "VPN policy updated")"; else status=failed; result="$(command_failed_result "failed to update VPN policy")"; fi
            ;;
        vpn.policy.delete)
            payload_file=/tmp/wrtmonitor-command-payload; printf '%s' "$command_payload" >"$payload_file"; policy_section="$(json_get_string "$payload_file" '@.section')"; policy_name="$(json_get_string "$payload_file" '@.name')"; rm -f "$payload_file"; policy_ref="${policy_section:-wrtmonitor_$policy_name}"; if uci -q delete "pbr.$policy_ref" && uci commit pbr && service_restart_if_enabled pbr config.enabled pbr >/dev/null 2>&1; then result="$(command_success_result "VPN policy deleted")"; else status=failed; result="$(command_failed_result "VPN policy not found")"; fi
            ;;
        *) return 1 ;;
    esac
    return 0
}
