from uuid import UUID, uuid5


CATALOG_VERSION = 2
PROFILE_NAMESPACE = UUID("eae76174-f176-4fae-9eec-f132974e7317")
NETIS_NX31_PROFILE_ID = UUID("7d92827e-2699-4ec1-814f-59a4894a0131")
BUILTIN_PROFILES = (
    {
        "id": NETIS_NX31_PROFILE_ID,
        "profile_key": "netis-nx31",
        "vendor": "Netis",
        "model": "NX31",
        "board_names": ["netis,nx31", "netis_nx31"],
        "compatibles": ["netis,nx31"],
        "target": "mediatek/filogic",
        "soc_vendor": "MediaTek",
        "soc_model": "MT7981B",
        "cpu_vendor": "Arm",
        "cpu_model": "Cortex-A53",
        "cpu_architecture": "aarch64",
        "cpu_cores": 2,
        "cpu_max_mhz": 1300,
        "sensor_roles": {
            "cpu-thermal": {"role": "soc", "label": "SoC MediaTek MT7981B"},
            "cpu_thermal": {"role": "soc", "label": "SoC MediaTek MT7981B"},
            "mt7981-thermal": {"role": "soc", "label": "SoC MediaTek MT7981B"},
            "mtk_thermal": {"role": "soc", "label": "SoC MediaTek MT7981B"},
            "mt7915_phy0": {"role": "radio_2g", "label": "Wi-Fi 2.4 ГГц"},
            "mt7915_phy1": {"role": "radio_5g", "label": "Wi-Fi 5 ГГц"},
        },
        "source_url": "https://openwrt.org/toh/hwdata/netis/netis_nx31",
    },
    {
        "id": uuid5(PROFILE_NAMESPACE, "bananapi-bpi-r3"),
        "profile_key": "bananapi-bpi-r3",
        "vendor": "Banana Pi",
        "model": "BPI-R3",
        "board_names": ["bananapi,bpi-r3"],
        "compatibles": ["bananapi,bpi-r3"],
        "target": "mediatek/filogic",
        "soc_vendor": "MediaTek",
        "soc_model": "MT7986A",
        "cpu_vendor": "Arm",
        "cpu_model": "Cortex-A53",
        "cpu_architecture": "aarch64",
        "cpu_cores": 4,
        "cpu_max_mhz": 2000,
        "sensor_roles": {},
        "source_url": "https://openwrt.org/toh/sinovoip/bananapi_bpi-r3",
    },
    {
        "id": uuid5(PROFILE_NAMESPACE, "xiaomi-ax3600"),
        "profile_key": "xiaomi-ax3600",
        "vendor": "Xiaomi",
        "model": "AX3600",
        "board_names": ["xiaomi,ax3600"],
        "compatibles": ["xiaomi,ax3600"],
        "target": "qualcommax/ipq807x",
        "soc_vendor": "Qualcomm",
        "soc_model": "IPQ8071A",
        "cpu_vendor": "Arm",
        "cpu_model": "Cortex-A53",
        "cpu_architecture": "aarch64",
        "cpu_cores": 4,
        "cpu_max_mhz": 1400,
        "sensor_roles": {},
        "source_url": "https://openwrt.org/toh/hwdata/xiaomi/xiaomi_ax3600",
    },
    {
        "id": uuid5(PROFILE_NAMESPACE, "friendlyarm-nanopi-r5s"),
        "profile_key": "friendlyarm-nanopi-r5s",
        "vendor": "FriendlyElec",
        "model": "NanoPi R5S",
        "board_names": ["friendlyarm,nanopi-r5s"],
        "compatibles": ["friendlyarm,nanopi-r5s"],
        "target": "rockchip/armv8",
        "soc_vendor": "Rockchip",
        "soc_model": "RK3568B2",
        "cpu_vendor": "Arm",
        "cpu_model": "Cortex-A55",
        "cpu_architecture": "aarch64",
        "cpu_cores": 4,
        "cpu_max_mhz": None,
        "sensor_roles": {},
        "source_url": "https://openwrt.org/toh/friendlyarm/nanopi_r5s",
    },
)
